# Generated by Django 3.1.7 on 2021-04-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dutyrota', '0002_auto_20210421_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='district',
            old_name='province',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='town',
            old_name='town',
            new_name='name',
        ),
    ]
