# Generated by Django 3.1.7 on 2021-04-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutyrota', '0004_onetimepassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='email',
            field=models.EmailField(default='scientistjackson0@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
