# Generated by Django 3.1.7 on 2021-04-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dutyrota', '0005_onetimepassword_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='otp',
            field=models.CharField(max_length=10),
        ),
    ]
