# Generated by Django 3.1.7 on 2021-04-15 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0002_auto_20210415_2208'),
        ('dutyrota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyRota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dutyrota.month')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dutyrota.day')),
                ('first_supervisor', models.ManyToManyField(related_name='_dutyrota_first_supervisor_+', to='teachers.Supervisor')),
                ('first_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teachers.teacher')),
                ('second_supervisor', models.ManyToManyField(related_name='_dutyrota_second_supervisor_+', to='teachers.Supervisor')),
                ('second_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='teachers.teacher')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dutyrota.term')),
                ('third_teacher_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
                ('week_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dutyrota.week')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dutyrota.year')),
            ],
        ),
    ]
