# Generated by Django 3.1.7 on 2021-04-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20210415_2208'),
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dutyrota',
            name='first_supervisor',
        ),
        migrations.RemoveField(
            model_name='dutyrota',
            name='first_teacher',
        ),
        migrations.RemoveField(
            model_name='dutyrota',
            name='second_supervisor',
        ),
        migrations.RemoveField(
            model_name='dutyrota',
            name='second_teacher',
        ),
        migrations.RemoveField(
            model_name='dutyrota',
            name='third_teacher_teacher',
        ),
        migrations.AddField(
            model_name='dutyrota',
            name='supervisors',
            field=models.ManyToManyField(related_name='_dutyrota_supervisors_+', to='teachers.Supervisor'),
        ),
        migrations.AddField(
            model_name='dutyrota',
            name='teachers',
            field=models.ManyToManyField(related_name='_dutyrota_teachers_+', to='teachers.Teacher'),
        ),
    ]
