# Generated by Django 3.1.7 on 2021-04-23 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dutyrota',
            name='school',
        ),
        migrations.RemoveField(
            model_name='leavepermission',
            name='school',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='school',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='school',
        ),
    ]
