# Generated by Django 3.1.7 on 2021-04-15 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dutyrota', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='other_name',
            new_name='other_names',
        ),
        migrations.AddField(
            model_name='person',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dutyrota.title'),
            preserve_default=False,
        ),
    ]
