# Generated by Django 3.1.7 on 2021-04-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20210415_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='other_names',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
