# Generated by Django 3.1.7 on 2021-04-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20210416_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(default='Science Department', max_length=50),
            preserve_default=False,
        ),
    ]
