# Generated by Django 3.1.7 on 2021-04-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacher_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
