# Generated by Django 3.1.7 on 2021-04-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pupil_name', models.CharField(max_length=50)),
                ('pupil_id', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('duration', models.CharField(max_length=30)),
            ],
        ),
    ]
