# Generated by Django 3.1.7 on 2021-04-19 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepermission',
            name='date_back',
            field=models.DateTimeField(default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavepermission',
            name='date_leaving',
            field=models.DateField(default=datetime.date(2021, 4, 19)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavepermission',
            name='pupil_email',
            field=models.EmailField(default='jack@jacktembo.com', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavepermission',
            name='pupil_phone',
            field=models.CharField(default='0971977252', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavepermission',
            name='time_leaving',
            field=models.TimeField(default=datetime.time(12, 0)),
            preserve_default=False,
        ),
    ]
