# Generated by Django 3.1.7 on 2021-04-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0002_auto_20210419_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavepermission',
            name='date_back',
            field=models.DateField(),
        ),
    ]
