# Generated by Django 3.1.7 on 2021-04-21 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0004_remove_leavepermission_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('pupil_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('parent_phone', models.CharField(max_length=15)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupils.grade')),
            ],
        ),
    ]
