# Generated by Django 3.1.7 on 2021-04-21 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0006_auto_20210421_1122'),
        ('pupils', '0005_grade_pupil'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepermission',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='routine.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pupil',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pupil',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='routine.school'),
            preserve_default=False,
        ),
    ]
